// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb-YKW9H9rdajTP-B3RDFbFj9ReqNuiwo',
    appId: '1:705155516030:web:40f0890262d82dc417fa2f',
    messagingSenderId: '705155516030',
    projectId: 'cen-pool-app',
    authDomain: 'cen-pool-app.firebaseapp.com',
    storageBucket: 'cen-pool-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSWjg21HJIOSTmcdWdVYM7AMgRBz2G42c',
    appId: '1:705155516030:android:16070b04b55a0aae17fa2f',
    messagingSenderId: '705155516030',
    projectId: 'cen-pool-app',
    storageBucket: 'cen-pool-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC9gsnotSdWNKlyqCJW55NmJkSF33y69g',
    appId: '1:705155516030:ios:9489b065a2f0a0ae17fa2f',
    messagingSenderId: '705155516030',
    projectId: 'cen-pool-app',
    storageBucket: 'cen-pool-app.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC9gsnotSdWNKlyqCJW55NmJkSF33y69g',
    appId: '1:705155516030:ios:b433bd46152f3cb417fa2f',
    messagingSenderId: '705155516030',
    projectId: 'cen-pool-app',
    storageBucket: 'cen-pool-app.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
